// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DuplicateSearch(arg1:Array<string>):Promise<Array<any>>;

export function Greet(arg1:string):Promise<Array<any>>;

export function PathSelect(arg1:string):Promise<string>;
