// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DuplicateSearch(arg1) {
  return window['go']['main']['App']['DuplicateSearch'](arg1);
}

export function Emulate() {
  return window['go']['main']['App']['Emulate']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PathSelect() {
  return window['go']['main']['App']['PathSelect']();
}
