// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFile(arg1:string):Promise<main.BoolReturn>;

export function DuplicateSearch(arg1:Array<string>):Promise<Array<any>>;

export function Emulate():Promise<Array<any>>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenPath(arg1:string):Promise<string>;

export function PathSelect():Promise<string>;
